// Generated by gencpp from file location_module/Location_Data_Type.msg
// DO NOT EDIT!


#ifndef LOCATION_MODULE_MESSAGE_LOCATION_DATA_TYPE_H
#define LOCATION_MODULE_MESSAGE_LOCATION_DATA_TYPE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace location_module
{
template <class ContainerAllocator>
struct Location_Data_Type_
{
  typedef Location_Data_Type_<ContainerAllocator> Type;

  Location_Data_Type_()
    : header()
    , X(0.0)
    , Y(0.0)
    , yaw(0.0)  {
    }
  Location_Data_Type_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , X(0.0)
    , Y(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _X_type;
  _X_type X;

   typedef double _Y_type;
  _Y_type Y;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::location_module::Location_Data_Type_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::location_module::Location_Data_Type_<ContainerAllocator> const> ConstPtr;

}; // struct Location_Data_Type_

typedef ::location_module::Location_Data_Type_<std::allocator<void> > Location_Data_Type;

typedef boost::shared_ptr< ::location_module::Location_Data_Type > Location_Data_TypePtr;
typedef boost::shared_ptr< ::location_module::Location_Data_Type const> Location_Data_TypeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::location_module::Location_Data_Type_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::location_module::Location_Data_Type_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace location_module

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'location_module': ['/home/neo/Location/src/location_module/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::location_module::Location_Data_Type_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::location_module::Location_Data_Type_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::location_module::Location_Data_Type_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::location_module::Location_Data_Type_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::location_module::Location_Data_Type_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::location_module::Location_Data_Type_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::location_module::Location_Data_Type_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4d623f5c802e74b951826b287a1cdd26";
  }

  static const char* value(const ::location_module::Location_Data_Type_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4d623f5c802e74b9ULL;
  static const uint64_t static_value2 = 0x51826b287a1cdd26ULL;
};

template<class ContainerAllocator>
struct DataType< ::location_module::Location_Data_Type_<ContainerAllocator> >
{
  static const char* value()
  {
    return "location_module/Location_Data_Type";
  }

  static const char* value(const ::location_module::Location_Data_Type_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::location_module::Location_Data_Type_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64 X\n\
float64 Y\n\
float64 yaw\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::location_module::Location_Data_Type_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::location_module::Location_Data_Type_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.X);
      stream.next(m.Y);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Location_Data_Type_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::location_module::Location_Data_Type_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::location_module::Location_Data_Type_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "X: ";
    Printer<double>::stream(s, indent + "  ", v.X);
    s << indent << "Y: ";
    Printer<double>::stream(s, indent + "  ", v.Y);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCATION_MODULE_MESSAGE_LOCATION_DATA_TYPE_H
