// Generated by gencpp from file ins_pub/INSCOV.msg
// DO NOT EDIT!


#ifndef INS_PUB_MESSAGE_INSCOV_H
#define INS_PUB_MESSAGE_INSCOV_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ins_pub
{
template <class ContainerAllocator>
struct INSCOV_
{
  typedef INSCOV_<ContainerAllocator> Type;

  INSCOV_()
    : header()
    , ros_time(0.0)
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , la_cov(0.0)
    , lon_cov(0.0)
    , high_cov(0.0)
    , N_vel(0.0)
    , E_vel(0.0)
    , U_vel(0.0)
    , N_vel_cov(0.0)
    , E_vel_cov(0.0)
    , U_vel_cov(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , roll_cov(0.0)
    , pitch_cov(0.0)
    , yaw_cov(0.0)
    , Undulation(0.0)
    , pos_type(0)
    , slo_status(0)  {
    }
  INSCOV_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ros_time(0.0)
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , la_cov(0.0)
    , lon_cov(0.0)
    , high_cov(0.0)
    , N_vel(0.0)
    , E_vel(0.0)
    , U_vel(0.0)
    , N_vel_cov(0.0)
    , E_vel_cov(0.0)
    , U_vel_cov(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , roll_cov(0.0)
    , pitch_cov(0.0)
    , yaw_cov(0.0)
    , Undulation(0.0)
    , pos_type(0)
    , slo_status(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _ros_time_type;
  _ros_time_type ros_time;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _altitude_type;
  _altitude_type altitude;

   typedef float _la_cov_type;
  _la_cov_type la_cov;

   typedef float _lon_cov_type;
  _lon_cov_type lon_cov;

   typedef float _high_cov_type;
  _high_cov_type high_cov;

   typedef double _N_vel_type;
  _N_vel_type N_vel;

   typedef double _E_vel_type;
  _E_vel_type E_vel;

   typedef double _U_vel_type;
  _U_vel_type U_vel;

   typedef float _N_vel_cov_type;
  _N_vel_cov_type N_vel_cov;

   typedef float _E_vel_cov_type;
  _E_vel_cov_type E_vel_cov;

   typedef float _U_vel_cov_type;
  _U_vel_cov_type U_vel_cov;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef float _roll_cov_type;
  _roll_cov_type roll_cov;

   typedef float _pitch_cov_type;
  _pitch_cov_type pitch_cov;

   typedef float _yaw_cov_type;
  _yaw_cov_type yaw_cov;

   typedef float _Undulation_type;
  _Undulation_type Undulation;

   typedef int32_t _pos_type_type;
  _pos_type_type pos_type;

   typedef int32_t _slo_status_type;
  _slo_status_type slo_status;





  typedef boost::shared_ptr< ::ins_pub::INSCOV_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ins_pub::INSCOV_<ContainerAllocator> const> ConstPtr;

}; // struct INSCOV_

typedef ::ins_pub::INSCOV_<std::allocator<void> > INSCOV;

typedef boost::shared_ptr< ::ins_pub::INSCOV > INSCOVPtr;
typedef boost::shared_ptr< ::ins_pub::INSCOV const> INSCOVConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ins_pub::INSCOV_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ins_pub::INSCOV_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ins_pub::INSCOV_<ContainerAllocator1> & lhs, const ::ins_pub::INSCOV_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ros_time == rhs.ros_time &&
    lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.altitude == rhs.altitude &&
    lhs.la_cov == rhs.la_cov &&
    lhs.lon_cov == rhs.lon_cov &&
    lhs.high_cov == rhs.high_cov &&
    lhs.N_vel == rhs.N_vel &&
    lhs.E_vel == rhs.E_vel &&
    lhs.U_vel == rhs.U_vel &&
    lhs.N_vel_cov == rhs.N_vel_cov &&
    lhs.E_vel_cov == rhs.E_vel_cov &&
    lhs.U_vel_cov == rhs.U_vel_cov &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw &&
    lhs.roll_cov == rhs.roll_cov &&
    lhs.pitch_cov == rhs.pitch_cov &&
    lhs.yaw_cov == rhs.yaw_cov &&
    lhs.Undulation == rhs.Undulation &&
    lhs.pos_type == rhs.pos_type &&
    lhs.slo_status == rhs.slo_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ins_pub::INSCOV_<ContainerAllocator1> & lhs, const ::ins_pub::INSCOV_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ins_pub

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ins_pub::INSCOV_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ins_pub::INSCOV_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ins_pub::INSCOV_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ins_pub::INSCOV_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ins_pub::INSCOV_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ins_pub::INSCOV_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ins_pub::INSCOV_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d88d99240050d1bc5588fd7460f53945";
  }

  static const char* value(const ::ins_pub::INSCOV_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd88d99240050d1bcULL;
  static const uint64_t static_value2 = 0x5588fd7460f53945ULL;
};

template<class ContainerAllocator>
struct DataType< ::ins_pub::INSCOV_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ins_pub/INSCOV";
  }

  static const char* value(const ::ins_pub::INSCOV_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ins_pub::INSCOV_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float64 ros_time\n"
"\n"
"float64 latitude\n"
"float64 longitude\n"
"float64 altitude\n"
"float32 la_cov\n"
"float32 lon_cov\n"
"float32 high_cov\n"
"\n"
"float64 N_vel\n"
"float64 E_vel\n"
"float64 U_vel\n"
"float32 N_vel_cov\n"
"float32 E_vel_cov\n"
"float32 U_vel_cov\n"
"\n"
"float64 roll\n"
"float64 pitch\n"
"float64 yaw\n"
"float32 roll_cov\n"
"float32 pitch_cov\n"
"float32 yaw_cov\n"
"float32 Undulation\n"
"int32 pos_type\n"
"int32 slo_status\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ins_pub::INSCOV_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ins_pub::INSCOV_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ros_time);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.altitude);
      stream.next(m.la_cov);
      stream.next(m.lon_cov);
      stream.next(m.high_cov);
      stream.next(m.N_vel);
      stream.next(m.E_vel);
      stream.next(m.U_vel);
      stream.next(m.N_vel_cov);
      stream.next(m.E_vel_cov);
      stream.next(m.U_vel_cov);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.roll_cov);
      stream.next(m.pitch_cov);
      stream.next(m.yaw_cov);
      stream.next(m.Undulation);
      stream.next(m.pos_type);
      stream.next(m.slo_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct INSCOV_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ins_pub::INSCOV_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ins_pub::INSCOV_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ros_time: ";
    Printer<double>::stream(s, indent + "  ", v.ros_time);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
    s << indent << "la_cov: ";
    Printer<float>::stream(s, indent + "  ", v.la_cov);
    s << indent << "lon_cov: ";
    Printer<float>::stream(s, indent + "  ", v.lon_cov);
    s << indent << "high_cov: ";
    Printer<float>::stream(s, indent + "  ", v.high_cov);
    s << indent << "N_vel: ";
    Printer<double>::stream(s, indent + "  ", v.N_vel);
    s << indent << "E_vel: ";
    Printer<double>::stream(s, indent + "  ", v.E_vel);
    s << indent << "U_vel: ";
    Printer<double>::stream(s, indent + "  ", v.U_vel);
    s << indent << "N_vel_cov: ";
    Printer<float>::stream(s, indent + "  ", v.N_vel_cov);
    s << indent << "E_vel_cov: ";
    Printer<float>::stream(s, indent + "  ", v.E_vel_cov);
    s << indent << "U_vel_cov: ";
    Printer<float>::stream(s, indent + "  ", v.U_vel_cov);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "roll_cov: ";
    Printer<float>::stream(s, indent + "  ", v.roll_cov);
    s << indent << "pitch_cov: ";
    Printer<float>::stream(s, indent + "  ", v.pitch_cov);
    s << indent << "yaw_cov: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_cov);
    s << indent << "Undulation: ";
    Printer<float>::stream(s, indent + "  ", v.Undulation);
    s << indent << "pos_type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pos_type);
    s << indent << "slo_status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.slo_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INS_PUB_MESSAGE_INSCOV_H
